# Web Scraping Lab

You will find in this notebook some scrapy exercises to practise your scraping skills.

**Tips:**

- Check the response status code for each request to ensure you have obtained the intended contennt.
- Print the response text in each request to understand the kind of info you are getting and its format.
- Check for patterns in the response text to extract the data/info requested in each question.
- Visit each url and take a look at its source through Chrome DevTools. You'll need to identify the html tags, special class names etc. used for the html content you are expected to extract.

- [Selenium Doc](https://www.selenium.dev/documentation/)
- [Requests library](http://docs.python-requests.org/en/master/#the-user-guide) documentation 
- [Urllib](https://docs.python.org/3/library/urllib.html#module-urllib)
- [re lib](https://docs.python.org/3/library/re.html)
- [lxml lib](https://lxml.de/)
- [Scrapy](https://scrapy.org/)
- [List of HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
- [HTML basics](http://www.simplehtmlguide.com/cheatsheet.php)
- [CSS basics](https://www.cssbasics.com/#page_start)

#### Below are the libraries and modules you may need. `Selenium` and `pandas` are imported for you.

In [46]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import time
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By

#### Enable the options you may need. In the next cell you have an example of them but you can choose to use them or not.

In [47]:
#driver configuration
opciones=Options()

opciones.add_experimental_option('excludeSwitches', ['enable-automation'])
opciones.add_experimental_option('useAutomationExtension', False)
opciones.headless=False    # si True, no aperece la ventana (headless=no visible)
opciones.add_argument('--start-maximized')         # comienza maximizado
#opciones.add_argument('user-data-dir=selenium')    # mantiene las cookies
#opciones.add_extension('driver_folder/adblock.crx')       # adblocker
opciones.add_argument('--incognito')

In [48]:
PATH=ChromeDriverManager().install()   # instala el driver

In [ ]:
#manualmente 
# driver = "./chromedriver.exe" #remember substitute this for your driver path
# driver = webdriver.Chrome(driver,options = opciones)

#### Download, parse, and print the content from the Trending Developers page from GitHub:

In [49]:
# This is the url you will scrape in this exercise
url = 'https://github.com/trending/developers'

In [50]:
#your code
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [ ]:
linktabla='/html/body/div[4]/main/div[3]'

In [61]:
tabla=driver.find_elements(By.CLASS_NAME, 'h3')
nombre= [e.text.strip() for e in tabla]
nombre

['Nikita Sobolev',
 'Emil Ernerfeldt',
 'Jonny Borges',
 'Stephen Celis',
 'monkeyWie',
 'Azure SDK Bot',
 'Martin Bonnin',
 'Wangchong Zhou',
 'Ammar Ahmed',
 'Matt Bierner',
 'Alessandro Ros',
 'Mike Perham',
 'DavidKorczynski',
 'Abhijeet Prasad',
 'Mislav Marohnić',
 'Leonard Hecker',
 'Pedro Cuenca',
 'Marcus Olsson',
 'Alex Eagle',
 'Nolan Lawson',
 'Luke Latham',
 'Joshua Levy',
 'Bas Nijholt',
 'Ice3man',
 'kunfei']

In [67]:
tabla_2=driver.find_elements(By.CLASS_NAME, 'f4')
alias= [e.text.strip() for e in tabla_2[2:25]]
alias

['sobolevn',
 'emilk',
 'jonataslaw',
 'stephencelis',
 'azure-sdk',
 'martinbonnin',
 'fffonion',
 'ammarahm-ed',
 'mjbvz',
 'aler9',
 'mperham',
 'AbhiPrasad',
 'mislav',
 'lhecker',
 'pcuenca',
 'marcusolsson',
 'alexeagle',
 'nolanlawson',
 'guardrex',
 'jlevy',
 'basnijholt',
 'Ice3man543',
 'gedoor']

In [68]:
for tabla, tabla_2 in zip(nombre, alias):
    print(f'{tabla}, ({tabla_2})')

Nikita Sobolev, (sobolevn)
Emil Ernerfeldt, (emilk)
Jonny Borges, (jonataslaw)
Stephen Celis, (stephencelis)
monkeyWie, (azure-sdk)
Azure SDK Bot, (martinbonnin)
Martin Bonnin, (fffonion)
Wangchong Zhou, (ammarahm-ed)
Ammar Ahmed, (mjbvz)
Matt Bierner, (aler9)
Alessandro Ros, (mperham)
Mike Perham, (AbhiPrasad)
DavidKorczynski, (mislav)
Abhijeet Prasad, (lhecker)
Mislav Marohnić, (pcuenca)
Leonard Hecker, (marcusolsson)
Pedro Cuenca, (alexeagle)
Marcus Olsson, (nolanlawson)
Alex Eagle, (guardrex)
Nolan Lawson, (jlevy)
Luke Latham, (basnijholt)
Joshua Levy, (Ice3man543)
Bas Nijholt, (gedoor)

In [93]:
driver.quit()

#### Display the names of the trending developers retrieved in the previous step.

Your output should be a Python list of developer names. Each name should not contain any html tag.

**Instructions:**

1. Find out the html tag and class names used for the developer names.

1. Use string manipulation techniques to replace whitespaces and linebreaks (i.e. `\n`) in the *text* of each html element. Use a list to store the clean names.

1. Print the list of names.

Your output should look like below:

```
['trimstray (@trimstray)',
 'joewalnes (JoeWalnes)',
 'charlax (Charles-AxelDein)',
 'ForrestKnight (ForrestKnight)',
 'revery-ui (revery-ui)',
 'alibaba (Alibaba)',
 'Microsoft (Microsoft)',
 'github (GitHub)',
 'facebook (Facebook)',
 'boazsegev (Bo)',
 'google (Google)',
 'cloudfetch',
 'sindresorhus (SindreSorhus)',
 'tensorflow',
 'apache (TheApacheSoftwareFoundation)',
 'DevonCrawford (DevonCrawford)',
 'ARMmbed (ArmMbed)',
 'vuejs (vuejs)',
 'fastai (fast.ai)',
 'QiShaoXuan (Qi)',
 'joelparkerhenderson (JoelParkerHenderson)',
 'torvalds (LinusTorvalds)',
 'CyC2018',
 'komeiji-satori (神楽坂覚々)',
 'script-8']
 ```

#### Display the trending Python repositories in GitHub

The steps to solve this problem is similar to the previous one except that you need to find out the repository names instead of developer names.

In [69]:
# This is the url you will scrape in this exercise
url = 'https://github.com/trending/python?since=daily'

In [70]:
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [74]:
names=driver.find_elements(By.CLASS_NAME, 'h3')
nombre= [e.text.strip().replace('/','') for e in names]
nombre

['public-apis  public-apis',
 'bregman-arie  devops-exercises',
 'facebookresearch  fairseq',
 'cloneofsimo  paint-with-words-sd',
 'Azure  azure-cli',
 'caronc  apprise',
 'joweich  chat-miner',
 'PaddlePaddle  PaddleTS',
 'mli  autocut',
 'sczhou  CodeFormer',
 'unifyai  ivy',
 'augmentedstartups  AS-One',
 'loTus04  W4SP-Stealer',
 'rwightman  pytorch-image-models',
 'iterativv  NostalgiaForInfinity',
 'getredash  redash',
 'ethereum  consensus-specs',
 'd8ahazard  sd_dreambooth_extension',
 'microsoft  recommenders',
 'zulip  zulip',
 'ultralytics  yolov5',
 'openai  improved-diffusion',
 'facebookresearch  ParlAI',
 'aliyun  surftrace',
 'NVlabs  stylegan2-ada-pytorch']

In [92]:
driver.quit()

#### Display all the image links from Walt Disney wikipedia page

In [75]:
# This is the url you will scrape in this exercise
url = 'https://en.wikipedia.org/wiki/Walt_Disney'

In [76]:
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [85]:
imagen=driver.find_elements(By.TAG_NAME, 'img')

In [90]:
[e.get_attribute('src') for e in imagen][:3]

['https://upload.wikimedia.org/wikipedia/en/thumb/e/e7/Cscr-featured.svg/20px-Cscr-featured.svg.png',
 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8c/Extended-protection-shackle.svg/20px-Extended-protection-shackle.svg.png',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Walt_Disney_1946.JPG/220px-Walt_Disney_1946.JPG']

In [91]:
driver.quit()

#### Retrieve an arbitary Wikipedia page of "Python" and create a list of links on that page

In [94]:
# This is the url you will scrape in this exercise
url ='https://en.wikipedia.org/wiki/Python'

In [95]:
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [106]:
wiki=driver.find_elements(By.TAG_NAME, 'a')
wiki[0]

In [104]:
[e.get_attribute('href') for e in wiki][1:5]

['https://en.wikipedia.org/wiki/Python#mw-head',
 'https://en.wikipedia.org/wiki/Python#searchInput',
 'https://en.wiktionary.org/wiki/Python',
 'https://en.wiktionary.org/wiki/python']

In [108]:
driver.quit()

#### Number of Titles that have changed in the United States Code since its last release point

In [109]:
# This is the url you will scrape in this exercise
url = 'http://uscode.house.gov/download/download.shtml'

In [110]:
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [125]:
us=driver.find_elements(By.CLASS_NAME, 'usctitlechanged')
us[0].text

'Title 17 - Copyrights ٭'

In [123]:
nombre= [e.text.strip() for e in us]
nombre

['Title 17 - Copyrights ٭',
 'Title 22 - Foreign Relations and Intercourse',
 "Title 38 - Veterans' Benefits ٭",
 'Title 40 - Public Buildings, Property, and Works ٭',
 'Title 41 - Public Contracts ٭',
 'Title 42 - The Public Health and Welfare',
 'Title 44 - Public Printing and Documents ٭',
 'Title 49 - Transportation ٭',
 'Title 54 - National Park Service and Related Programs ٭']

In [126]:
driver.quit()

#### A Python list with the top ten FBI's Most Wanted names

In [127]:
# This is the url you will scrape in this exercise
url = 'https://www.fbi.gov/wanted/topten'

In [128]:
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [137]:
fbi=driver.find_elements(By.CLASS_NAME, 'title')
fbi[1].text

'OMAR ALEXANDER CARDENAS'

In [139]:
nombre= [e.text.strip() for e in fbi]
nombre

['MOST WANTED',
 'OMAR ALEXANDER CARDENAS',
 'ALEXIS FLORES',
 'JOSE RODOLFO VILLARREAL-HERNANDEZ',
 'YULAN ADONAY ARCHAGA CARIAS',
 'BHADRESHKUMAR CHETANBHAI PATEL',
 'ALEJANDRO ROSALES CASTILLO',
 'MICHAEL JAMES PRATT',
 'RUJA IGNATOVA',
 'ARNOLDO JIMENEZ',
 'RAFAEL CARO-QUINTERO']

In [140]:
driver.quit()

####  20 latest earthquakes info (date, time, latitude, longitude and region name) by the EMSC as a pandas dataframe

In [202]:
# This is the url you will scrape in this exercise
url = 'https://www.emsc-csem.org/Earthquake/'

In [203]:
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [241]:
tabla=driver.find_element(By.XPATH, '/html/body')

filas=tabla.find_elements(By.CLASS_NAME, 'normal')


data=[]


for f in filas:
    
    elemen=f.find_elements(By.TAG_NAME, 'td')
    
    tmp=[]
    
    for e in elemen:
        
        tmp.append(e.text)
        
    data.append(tmp)

    
data

[['',
  '',
  '',
  '2022-11-09   16:57:20.7\n15min ago',
  '38.09 ',
  'S  ',
  '176.65 ',
  'E  ',
  '5',
  '',
  '3.0',
  ' NORTH ISLAND OF NEW ZEALAND',
  ''],
 ['',
  '',
  '',
  '2022-11-09   16:50:09.7\n23min ago',
  '43.91 ',
  'N  ',
  '13.31 ',
  'E  ',
  '7',
  '',
  '2.3',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   16:50:02.0\n23min ago',
  '15.10 ',
  'N  ',
  '94.37 ',
  'W  ',
  '16',
  '',
  '4.2',
  ' OFF COAST OF CHIAPAS, MEXICO',
  ''],
 ['',
  '',
  '',
  '2022-11-09   16:43:54.0\n29min ago',
  '10.16 ',
  'S  ',
  '118.81 ',
  'E  ',
  '10',
  '',
  '3.4',
  ' SOUTH OF SUMBAWA, INDONESIA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   16:41:19.4\n31min ago',
  '19.18 ',
  'N  ',
  '155.49 ',
  'W  ',
  '36',
  '',
  '2.2',
  ' ISLAND OF HAWAII, HAWAII',
  ''],
 ['',
  '',
  '',
  '2022-11-09   16:38:20.0\n34min ago',
  '10.13 ',
  'S  ',
  '118.82 ',
  'E  ',
  '10',
  '',
  '3.4',
  ' SOUTH OF SUMBAWA, INDONESIA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   16:10:36.3\n1hr 02min ago',
  '43.95 ',
  'N  ',
  '13.29 ',
  'E  ',
  '2',
  '',
  '2.5',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   16:07:15.2\n1hr 06min ago',
  '34.55 ',
  'N  ',
  '23.87 ',
  'E  ',
  '21',
  '',
  '2.7',
  ' CRETE, GREECE',
  ''],
 ['',
  '',
  '',
  '2022-11-09   15:58:32.1\n1hr 14min ago',
  '37.07 ',
  'N  ',
  '28.38 ',
  'E  ',
  '9',
  '',
  '2.9',
  ' WESTERN TURKEY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   15:40:34.6\n1hr 32min ago',
  '43.97 ',
  'N  ',
  '13.33 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   15:37:05.0\n1hr 36min ago',
  '21.53 ',
  'S  ',
  '68.57 ',
  'W  ',
  '115',
  '',
  '2.9',
  ' ANTOFAGASTA, CHILE',
  ''],
 ['',
  '',
  '',
  '2022-11-09   15:26:21.9\n1hr 46min ago',
  '44.01 ',
  'N  ',
  '13.28 ',
  'E  ',
  '26',
  '',
  '2.4',
  ' ADRIATIC SEA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   15:23:39.1\n1hr 49min ago',
  '44.00 ',
  'N  ',
  '13.30 ',
  'E  ',
  '9',
  '',
  '2.2',
  ' ADRIATIC SEA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   15:06:55.0\n2hr 06min ago',
  '12.70 ',
  'N  ',
  '88.19 ',
  'W  ',
  '33',
  '',
  '2.6',
  ' OFFSHORE EL SALVADOR',
  ''],
 ['',
  '',
  '',
  '2022-11-09   14:58:24.0\n2hr 14min ago',
  '17.32 ',
  'N  ',
  '100.83 ',
  'W  ',
  '12',
  '',
  '4.3',
  ' GUERRERO, MEXICO',
  ''],
 ['',
  '',
  '',
  '2022-11-09   14:51:54.6\n2hr 21min ago',
  '35.91 ',
  'N  ',
  '90.01 ',
  'W  ',
  '7',
  '',
  '2.4',
  ' ARKANSAS',
  ''],
 ['',
  '',
  '',
  '2022-11-09   14:47:27.1\n2hr 25min ago',
  '43.92 ',
  'N  ',
  '13.26 ',
  'E  ',
  '13',
  '',
  '2.3',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   14:10:53.7\n3hr 02min ago',
  '35.91 ',
  'N  ',
  '117.71 ',
  'W  ',
  '2',
  '',
  '2.1',
  ' CENTRAL CALIFORNIA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:54:07.6\n3hr 19min ago',
  '43.95 ',
  'N  ',
  '13.29 ',
  'E  ',
  '10',
  '',
  '2.0',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:48:48.8\n3hr 24min ago',
  '40.16 ',
  'N  ',
  '119.14 ',
  'W  ',
  '8',
  '',
  '2.6',
  ' NEVADA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:41:43.0\n3hr 31min ago',
  '3.02 ',
  'S  ',
  '122.04 ',
  'E  ',
  '10',
  '',
  '3.1',
  ' SULAWESI, INDONESIA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:37:46.8\n3hr 35min ago',
  '43.95 ',
  'N  ',
  '13.31 ',
  'E  ',
  '9',
  '',
  '2.6',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:34:23.2\n3hr 38min ago',
  '43.95 ',
  'N  ',
  '13.36 ',
  'E  ',
  '7',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:34:05.0\n3hr 39min ago',
  '64.02 ',
  'N  ',
  '21.35 ',
  'W  ',
  '5',
  '',
  '3.2',
  ' ICELAND',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:21:37.0\n3hr 51min ago',
  '27.89 ',
  'S  ',
  '66.75 ',
  'W  ',
  '182',
  '',
  '3.1',
  ' CATAMARCA, ARGENTINA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:19:03.0\n3hr 54min ago',
  '11.55 ',
  'N  ',
  '87.48 ',
  'W  ',
  '30',
  '',
  '3.0',
  ' NEAR COAST OF NICARAGUA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:16:24.1\n3hr 56min ago',
  '45.65 ',
  'N  ',
  '26.61 ',
  'E  ',
  '82',
  '',
  '2.8',
  ' ROMANIA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:08:41.0\n4hr 04min ago',
  '18.88 ',
  'N  ',
  '121.95 ',
  'E  ',
  '113',
  '',
  '3.2',
  ' LUZON, PHILIPPINES',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:08:02.0\n4hr 05min ago',
  '22.20 ',
  'S  ',
  '68.71 ',
  'W  ',
  '112',
  '',
  '2.8',
  ' ANTOFAGASTA, CHILE',
  ''],
 ['',
  '',
  '',
  '2022-11-09   13:00:04.7\n4hr 13min ago',
  '19.38 ',
  'N  ',
  '66.34 ',
  'W  ',
  '11',
  '',
  '3.6',
  ' PUERTO RICO REGION',
  ''],
 ['',
  '',
  '',
  '2022-11-09   12:54:30.9\n4hr 18min ago',
  '58.51 ',
  'N  ',
  '152.25 ',
  'W  ',
  '35',
  '',
  '2.6',
  ' KODIAK ISLAND REGION, ALASKA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   12:52:25.0\n4hr 20min ago',
  '1.67 ',
  'N  ',
  '127.04 ',
  'E  ',
  '27',
  '',
  '4.3',
  ' HALMAHERA, INDONESIA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   12:51:38.5\n4hr 21min ago',
  '49.32 ',
  'N  ',
  '156.05 ',
  'E  ',
  '50',
  '',
  '4.4',
  ' KURIL ISLANDS',
  ''],
 ['',
  '',
  '',
  '2022-11-09   12:45:59.0\n4hr 27min ago',
  '27.80 ',
  'S  ',
  '71.24 ',
  'W  ',
  '11',
  '',
  '2.8',
  ' OFFSHORE ATACAMA, CHILE',
  ''],
 ['',
  '',
  '',
  '2022-11-09   12:44:13.5\n4hr 29min ago',
  '43.98 ',
  'N  ',
  '13.27 ',
  'E  ',
  '10',
  '',
  '2.4',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   12:33:52.0\n4hr 39min ago',
  '43.90 ',
  'N  ',
  '13.39 ',
  'E  ',
  '8',
  '',
  '2.3',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   12:29:54.0\n4hr 43min ago',
  '33.05 ',
  'S  ',
  '68.16 ',
  'W  ',
  '10',
  '',
  '3.1',
  ' MENDOZA, ARGENTINA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   12:20:59.8\n4hr 52min ago',
  '43.96 ',
  'N  ',
  '13.33 ',
  'E  ',
  '9',
  '',
  '2.0',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   12:13:03.6\n5hr 00min ago',
  '43.95 ',
  'N  ',
  '13.32 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   12:10:37.9\n5hr 02min ago',
  '19.16 ',
  'N  ',
  '155.38 ',
  'W  ',
  '36',
  '',
  '2.6',
  ' ISLAND OF HAWAII, HAWAII',
  ''],
 ['6',
  '',
  'III',
  '2022-11-09   12:10:05.4\n5hr 03min ago',
  '44.05 ',
  'N  ',
  '13.31 ',
  'E  ',
  '26',
  '',
  '3.9',
  ' ADRIATIC SEA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   12:02:56.2\n5hr 10min ago',
  '44.01 ',
  'N  ',
  '13.27 ',
  'E  ',
  '8',
  '',
  '3.1',
  ' ADRIATIC SEA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   11:50:55.0\n5hr 22min ago',
  '8.40 ',
  'S  ',
  '119.82 ',
  'E  ',
  '142',
  '',
  '3.2',
  ' FLORES REGION, INDONESIA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   11:46:06.2\n5hr 27min ago',
  '19.10 ',
  'N  ',
  '155.42 ',
  'W  ',
  '30',
  '',
  '2.0',
  ' ISLAND OF HAWAII, HAWAII',
  ''],
 ['',
  '',
  '',
  '2022-11-09   11:41:07.0\n5hr 32min ago',
  '2.98 ',
  'S  ',
  '140.05 ',
  'E  ',
  '16',
  '',
  '2.7',
  ' NEAR N COAST OF PAPUA, INDONESIA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   11:10:29.0\n6hr 02min ago',
  '11.50 ',
  'N  ',
  '87.50 ',
  'W  ',
  '78',
  '',
  '2.7',
  ' NEAR COAST OF NICARAGUA',
  ''],
 ['',
  '',
  '',
  '2022-11-09   11:09:26.0\n6hr 03min ago',
  '18.21 ',
  'N  ',
  '103.59 ',
  'W  ',
  '5',
  '',
  '4.1',
  ' OFFSHORE MICHOACAN, MEXICO',
  ''],
 ['1',
  '',
  'F',
  '2022-11-09   11:08:33.7\n6hr 04min ago',
  '39.89 ',
  'N  ',
  '15.74 ',
  'E  ',
  '16',
  '',
  '2.6',
  ' SOUTHERN ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   11:03:23.9\n6hr 09min ago',
  '43.91 ',
  'N  ',
  '13.34 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['',
  '',
  '',
  '2022-11-09   11:01:42.9\n6hr 11min ago',
  '43.90 ',
  'N  ',
  '13.24 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  '']]

In [242]:
for e in range(len(data)):
    data[e]=data[e][3:]

In [243]:
data

[['2022-11-09   16:57:20.7\n15min ago',
  '38.09 ',
  'S  ',
  '176.65 ',
  'E  ',
  '5',
  '',
  '3.0',
  ' NORTH ISLAND OF NEW ZEALAND',
  ''],
 ['2022-11-09   16:50:09.7\n23min ago',
  '43.91 ',
  'N  ',
  '13.31 ',
  'E  ',
  '7',
  '',
  '2.3',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   16:50:02.0\n23min ago',
  '15.10 ',
  'N  ',
  '94.37 ',
  'W  ',
  '16',
  '',
  '4.2',
  ' OFF COAST OF CHIAPAS, MEXICO',
  ''],
 ['2022-11-09   16:43:54.0\n29min ago',
  '10.16 ',
  'S  ',
  '118.81 ',
  'E  ',
  '10',
  '',
  '3.4',
  ' SOUTH OF SUMBAWA, INDONESIA',
  ''],
 ['2022-11-09   16:41:19.4\n31min ago',
  '19.18 ',
  'N  ',
  '155.49 ',
  'W  ',
  '36',
  '',
  '2.2',
  ' ISLAND OF HAWAII, HAWAII',
  ''],
 ['2022-11-09   16:38:20.0\n34min ago',
  '10.13 ',
  'S  ',
  '118.82 ',
  'E  ',
  '10',
  '',
  '3.4',
  ' SOUTH OF SUMBAWA, INDONESIA',
  ''],
 ['2022-11-09   16:10:36.3\n1hr 02min ago',
  '43.95 ',
  'N  ',
  '13.29 ',
  'E  ',
  '2',
  '',
  '2.5',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   16:07:15.2\n1hr 06min ago',
  '34.55 ',
  'N  ',
  '23.87 ',
  'E  ',
  '21',
  '',
  '2.7',
  ' CRETE, GREECE',
  ''],
 ['2022-11-09   15:58:32.1\n1hr 14min ago',
  '37.07 ',
  'N  ',
  '28.38 ',
  'E  ',
  '9',
  '',
  '2.9',
  ' WESTERN TURKEY',
  ''],
 ['2022-11-09   15:40:34.6\n1hr 32min ago',
  '43.97 ',
  'N  ',
  '13.33 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   15:37:05.0\n1hr 36min ago',
  '21.53 ',
  'S  ',
  '68.57 ',
  'W  ',
  '115',
  '',
  '2.9',
  ' ANTOFAGASTA, CHILE',
  ''],
 ['2022-11-09   15:26:21.9\n1hr 46min ago',
  '44.01 ',
  'N  ',
  '13.28 ',
  'E  ',
  '26',
  '',
  '2.4',
  ' ADRIATIC SEA',
  ''],
 ['2022-11-09   15:23:39.1\n1hr 49min ago',
  '44.00 ',
  'N  ',
  '13.30 ',
  'E  ',
  '9',
  '',
  '2.2',
  ' ADRIATIC SEA',
  ''],
 ['2022-11-09   15:06:55.0\n2hr 06min ago',
  '12.70 ',
  'N  ',
  '88.19 ',
  'W  ',
  '33',
  '',
  '2.6',
  ' OFFSHORE EL SALVADOR',
  ''],
 ['2022-11-09   14:58:24.0\n2hr 14min ago',
  '17.32 ',
  'N  ',
  '100.83 ',
  'W  ',
  '12',
  '',
  '4.3',
  ' GUERRERO, MEXICO',
  ''],
 ['2022-11-09   14:51:54.6\n2hr 21min ago',
  '35.91 ',
  'N  ',
  '90.01 ',
  'W  ',
  '7',
  '',
  '2.4',
  ' ARKANSAS',
  ''],
 ['2022-11-09   14:47:27.1\n2hr 25min ago',
  '43.92 ',
  'N  ',
  '13.26 ',
  'E  ',
  '13',
  '',
  '2.3',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   14:10:53.7\n3hr 02min ago',
  '35.91 ',
  'N  ',
  '117.71 ',
  'W  ',
  '2',
  '',
  '2.1',
  ' CENTRAL CALIFORNIA',
  ''],
 ['2022-11-09   13:54:07.6\n3hr 19min ago',
  '43.95 ',
  'N  ',
  '13.29 ',
  'E  ',
  '10',
  '',
  '2.0',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   13:48:48.8\n3hr 24min ago',
  '40.16 ',
  'N  ',
  '119.14 ',
  'W  ',
  '8',
  '',
  '2.6',
  ' NEVADA',
  ''],
 ['2022-11-09   13:41:43.0\n3hr 31min ago',
  '3.02 ',
  'S  ',
  '122.04 ',
  'E  ',
  '10',
  '',
  '3.1',
  ' SULAWESI, INDONESIA',
  ''],
 ['2022-11-09   13:37:46.8\n3hr 35min ago',
  '43.95 ',
  'N  ',
  '13.31 ',
  'E  ',
  '9',
  '',
  '2.6',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   13:34:23.2\n3hr 38min ago',
  '43.95 ',
  'N  ',
  '13.36 ',
  'E  ',
  '7',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   13:34:05.0\n3hr 39min ago',
  '64.02 ',
  'N  ',
  '21.35 ',
  'W  ',
  '5',
  '',
  '3.2',
  ' ICELAND',
  ''],
 ['2022-11-09   13:21:37.0\n3hr 51min ago',
  '27.89 ',
  'S  ',
  '66.75 ',
  'W  ',
  '182',
  '',
  '3.1',
  ' CATAMARCA, ARGENTINA',
  ''],
 ['2022-11-09   13:19:03.0\n3hr 54min ago',
  '11.55 ',
  'N  ',
  '87.48 ',
  'W  ',
  '30',
  '',
  '3.0',
  ' NEAR COAST OF NICARAGUA',
  ''],
 ['2022-11-09   13:16:24.1\n3hr 56min ago',
  '45.65 ',
  'N  ',
  '26.61 ',
  'E  ',
  '82',
  '',
  '2.8',
  ' ROMANIA',
  ''],
 ['2022-11-09   13:08:41.0\n4hr 04min ago',
  '18.88 ',
  'N  ',
  '121.95 ',
  'E  ',
  '113',
  '',
  '3.2',
  ' LUZON, PHILIPPINES',
  ''],
 ['2022-11-09   13:08:02.0\n4hr 05min ago',
  '22.20 ',
  'S  ',
  '68.71 ',
  'W  ',
  '112',
  '',
  '2.8',
  ' ANTOFAGASTA, CHILE',
  ''],
 ['2022-11-09   13:00:04.7\n4hr 13min ago',
  '19.38 ',
  'N  ',
  '66.34 ',
  'W  ',
  '11',
  '',
  '3.6',
  ' PUERTO RICO REGION',
  ''],
 ['2022-11-09   12:54:30.9\n4hr 18min ago',
  '58.51 ',
  'N  ',
  '152.25 ',
  'W  ',
  '35',
  '',
  '2.6',
  ' KODIAK ISLAND REGION, ALASKA',
  ''],
 ['2022-11-09   12:52:25.0\n4hr 20min ago',
  '1.67 ',
  'N  ',
  '127.04 ',
  'E  ',
  '27',
  '',
  '4.3',
  ' HALMAHERA, INDONESIA',
  ''],
 ['2022-11-09   12:51:38.5\n4hr 21min ago',
  '49.32 ',
  'N  ',
  '156.05 ',
  'E  ',
  '50',
  '',
  '4.4',
  ' KURIL ISLANDS',
  ''],
 ['2022-11-09   12:45:59.0\n4hr 27min ago',
  '27.80 ',
  'S  ',
  '71.24 ',
  'W  ',
  '11',
  '',
  '2.8',
  ' OFFSHORE ATACAMA, CHILE',
  ''],
 ['2022-11-09   12:44:13.5\n4hr 29min ago',
  '43.98 ',
  'N  ',
  '13.27 ',
  'E  ',
  '10',
  '',
  '2.4',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   12:33:52.0\n4hr 39min ago',
  '43.90 ',
  'N  ',
  '13.39 ',
  'E  ',
  '8',
  '',
  '2.3',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   12:29:54.0\n4hr 43min ago',
  '33.05 ',
  'S  ',
  '68.16 ',
  'W  ',
  '10',
  '',
  '3.1',
  ' MENDOZA, ARGENTINA',
  ''],
 ['2022-11-09   12:20:59.8\n4hr 52min ago',
  '43.96 ',
  'N  ',
  '13.33 ',
  'E  ',
  '9',
  '',
  '2.0',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   12:13:03.6\n5hr 00min ago',
  '43.95 ',
  'N  ',
  '13.32 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   12:10:37.9\n5hr 02min ago',
  '19.16 ',
  'N  ',
  '155.38 ',
  'W  ',
  '36',
  '',
  '2.6',
  ' ISLAND OF HAWAII, HAWAII',
  ''],
 ['2022-11-09   12:10:05.4\n5hr 03min ago',
  '44.05 ',
  'N  ',
  '13.31 ',
  'E  ',
  '26',
  '',
  '3.9',
  ' ADRIATIC SEA',
  ''],
 ['2022-11-09   12:02:56.2\n5hr 10min ago',
  '44.01 ',
  'N  ',
  '13.27 ',
  'E  ',
  '8',
  '',
  '3.1',
  ' ADRIATIC SEA',
  ''],
 ['2022-11-09   11:50:55.0\n5hr 22min ago',
  '8.40 ',
  'S  ',
  '119.82 ',
  'E  ',
  '142',
  '',
  '3.2',
  ' FLORES REGION, INDONESIA',
  ''],
 ['2022-11-09   11:46:06.2\n5hr 27min ago',
  '19.10 ',
  'N  ',
  '155.42 ',
  'W  ',
  '30',
  '',
  '2.0',
  ' ISLAND OF HAWAII, HAWAII',
  ''],
 ['2022-11-09   11:41:07.0\n5hr 32min ago',
  '2.98 ',
  'S  ',
  '140.05 ',
  'E  ',
  '16',
  '',
  '2.7',
  ' NEAR N COAST OF PAPUA, INDONESIA',
  ''],
 ['2022-11-09   11:10:29.0\n6hr 02min ago',
  '11.50 ',
  'N  ',
  '87.50 ',
  'W  ',
  '78',
  '',
  '2.7',
  ' NEAR COAST OF NICARAGUA',
  ''],
 ['2022-11-09   11:09:26.0\n6hr 03min ago',
  '18.21 ',
  'N  ',
  '103.59 ',
  'W  ',
  '5',
  '',
  '4.1',
  ' OFFSHORE MICHOACAN, MEXICO',
  ''],
 ['2022-11-09   11:08:33.7\n6hr 04min ago',
  '39.89 ',
  'N  ',
  '15.74 ',
  'E  ',
  '16',
  '',
  '2.6',
  ' SOUTHERN ITALY',
  ''],
 ['2022-11-09   11:03:23.9\n6hr 09min ago',
  '43.91 ',
  'N  ',
  '13.34 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   11:01:42.9\n6hr 11min ago',
  '43.90 ',
  'N  ',
  '13.24 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  '']]

In [245]:
fecha=[]
latitud=[]
longitud=[]
area=[]


for i in range(len(data)):
    fecha.append(data[i][0])
    latitud.append(data[i][1:2])
    longitud.append(data[i][3:4])
    area.append(data[i][8])

In [246]:
data

[['2022-11-09   16:57:20.7\n15min ago',
  '38.09 ',
  'S  ',
  '176.65 ',
  'E  ',
  '5',
  '',
  '3.0',
  ' NORTH ISLAND OF NEW ZEALAND',
  ''],
 ['2022-11-09   16:50:09.7\n23min ago',
  '43.91 ',
  'N  ',
  '13.31 ',
  'E  ',
  '7',
  '',
  '2.3',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   16:50:02.0\n23min ago',
  '15.10 ',
  'N  ',
  '94.37 ',
  'W  ',
  '16',
  '',
  '4.2',
  ' OFF COAST OF CHIAPAS, MEXICO',
  ''],
 ['2022-11-09   16:43:54.0\n29min ago',
  '10.16 ',
  'S  ',
  '118.81 ',
  'E  ',
  '10',
  '',
  '3.4',
  ' SOUTH OF SUMBAWA, INDONESIA',
  ''],
 ['2022-11-09   16:41:19.4\n31min ago',
  '19.18 ',
  'N  ',
  '155.49 ',
  'W  ',
  '36',
  '',
  '2.2',
  ' ISLAND OF HAWAII, HAWAII',
  ''],
 ['2022-11-09   16:38:20.0\n34min ago',
  '10.13 ',
  'S  ',
  '118.82 ',
  'E  ',
  '10',
  '',
  '3.4',
  ' SOUTH OF SUMBAWA, INDONESIA',
  ''],
 ['2022-11-09   16:10:36.3\n1hr 02min ago',
  '43.95 ',
  'N  ',
  '13.29 ',
  'E  ',
  '2',
  '',
  '2.5',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   16:07:15.2\n1hr 06min ago',
  '34.55 ',
  'N  ',
  '23.87 ',
  'E  ',
  '21',
  '',
  '2.7',
  ' CRETE, GREECE',
  ''],
 ['2022-11-09   15:58:32.1\n1hr 14min ago',
  '37.07 ',
  'N  ',
  '28.38 ',
  'E  ',
  '9',
  '',
  '2.9',
  ' WESTERN TURKEY',
  ''],
 ['2022-11-09   15:40:34.6\n1hr 32min ago',
  '43.97 ',
  'N  ',
  '13.33 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   15:37:05.0\n1hr 36min ago',
  '21.53 ',
  'S  ',
  '68.57 ',
  'W  ',
  '115',
  '',
  '2.9',
  ' ANTOFAGASTA, CHILE',
  ''],
 ['2022-11-09   15:26:21.9\n1hr 46min ago',
  '44.01 ',
  'N  ',
  '13.28 ',
  'E  ',
  '26',
  '',
  '2.4',
  ' ADRIATIC SEA',
  ''],
 ['2022-11-09   15:23:39.1\n1hr 49min ago',
  '44.00 ',
  'N  ',
  '13.30 ',
  'E  ',
  '9',
  '',
  '2.2',
  ' ADRIATIC SEA',
  ''],
 ['2022-11-09   15:06:55.0\n2hr 06min ago',
  '12.70 ',
  'N  ',
  '88.19 ',
  'W  ',
  '33',
  '',
  '2.6',
  ' OFFSHORE EL SALVADOR',
  ''],
 ['2022-11-09   14:58:24.0\n2hr 14min ago',
  '17.32 ',
  'N  ',
  '100.83 ',
  'W  ',
  '12',
  '',
  '4.3',
  ' GUERRERO, MEXICO',
  ''],
 ['2022-11-09   14:51:54.6\n2hr 21min ago',
  '35.91 ',
  'N  ',
  '90.01 ',
  'W  ',
  '7',
  '',
  '2.4',
  ' ARKANSAS',
  ''],
 ['2022-11-09   14:47:27.1\n2hr 25min ago',
  '43.92 ',
  'N  ',
  '13.26 ',
  'E  ',
  '13',
  '',
  '2.3',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   14:10:53.7\n3hr 02min ago',
  '35.91 ',
  'N  ',
  '117.71 ',
  'W  ',
  '2',
  '',
  '2.1',
  ' CENTRAL CALIFORNIA',
  ''],
 ['2022-11-09   13:54:07.6\n3hr 19min ago',
  '43.95 ',
  'N  ',
  '13.29 ',
  'E  ',
  '10',
  '',
  '2.0',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   13:48:48.8\n3hr 24min ago',
  '40.16 ',
  'N  ',
  '119.14 ',
  'W  ',
  '8',
  '',
  '2.6',
  ' NEVADA',
  ''],
 ['2022-11-09   13:41:43.0\n3hr 31min ago',
  '3.02 ',
  'S  ',
  '122.04 ',
  'E  ',
  '10',
  '',
  '3.1',
  ' SULAWESI, INDONESIA',
  ''],
 ['2022-11-09   13:37:46.8\n3hr 35min ago',
  '43.95 ',
  'N  ',
  '13.31 ',
  'E  ',
  '9',
  '',
  '2.6',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   13:34:23.2\n3hr 38min ago',
  '43.95 ',
  'N  ',
  '13.36 ',
  'E  ',
  '7',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   13:34:05.0\n3hr 39min ago',
  '64.02 ',
  'N  ',
  '21.35 ',
  'W  ',
  '5',
  '',
  '3.2',
  ' ICELAND',
  ''],
 ['2022-11-09   13:21:37.0\n3hr 51min ago',
  '27.89 ',
  'S  ',
  '66.75 ',
  'W  ',
  '182',
  '',
  '3.1',
  ' CATAMARCA, ARGENTINA',
  ''],
 ['2022-11-09   13:19:03.0\n3hr 54min ago',
  '11.55 ',
  'N  ',
  '87.48 ',
  'W  ',
  '30',
  '',
  '3.0',
  ' NEAR COAST OF NICARAGUA',
  ''],
 ['2022-11-09   13:16:24.1\n3hr 56min ago',
  '45.65 ',
  'N  ',
  '26.61 ',
  'E  ',
  '82',
  '',
  '2.8',
  ' ROMANIA',
  ''],
 ['2022-11-09   13:08:41.0\n4hr 04min ago',
  '18.88 ',
  'N  ',
  '121.95 ',
  'E  ',
  '113',
  '',
  '3.2',
  ' LUZON, PHILIPPINES',
  ''],
 ['2022-11-09   13:08:02.0\n4hr 05min ago',
  '22.20 ',
  'S  ',
  '68.71 ',
  'W  ',
  '112',
  '',
  '2.8',
  ' ANTOFAGASTA, CHILE',
  ''],
 ['2022-11-09   13:00:04.7\n4hr 13min ago',
  '19.38 ',
  'N  ',
  '66.34 ',
  'W  ',
  '11',
  '',
  '3.6',
  ' PUERTO RICO REGION',
  ''],
 ['2022-11-09   12:54:30.9\n4hr 18min ago',
  '58.51 ',
  'N  ',
  '152.25 ',
  'W  ',
  '35',
  '',
  '2.6',
  ' KODIAK ISLAND REGION, ALASKA',
  ''],
 ['2022-11-09   12:52:25.0\n4hr 20min ago',
  '1.67 ',
  'N  ',
  '127.04 ',
  'E  ',
  '27',
  '',
  '4.3',
  ' HALMAHERA, INDONESIA',
  ''],
 ['2022-11-09   12:51:38.5\n4hr 21min ago',
  '49.32 ',
  'N  ',
  '156.05 ',
  'E  ',
  '50',
  '',
  '4.4',
  ' KURIL ISLANDS',
  ''],
 ['2022-11-09   12:45:59.0\n4hr 27min ago',
  '27.80 ',
  'S  ',
  '71.24 ',
  'W  ',
  '11',
  '',
  '2.8',
  ' OFFSHORE ATACAMA, CHILE',
  ''],
 ['2022-11-09   12:44:13.5\n4hr 29min ago',
  '43.98 ',
  'N  ',
  '13.27 ',
  'E  ',
  '10',
  '',
  '2.4',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   12:33:52.0\n4hr 39min ago',
  '43.90 ',
  'N  ',
  '13.39 ',
  'E  ',
  '8',
  '',
  '2.3',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   12:29:54.0\n4hr 43min ago',
  '33.05 ',
  'S  ',
  '68.16 ',
  'W  ',
  '10',
  '',
  '3.1',
  ' MENDOZA, ARGENTINA',
  ''],
 ['2022-11-09   12:20:59.8\n4hr 52min ago',
  '43.96 ',
  'N  ',
  '13.33 ',
  'E  ',
  '9',
  '',
  '2.0',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   12:13:03.6\n5hr 00min ago',
  '43.95 ',
  'N  ',
  '13.32 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   12:10:37.9\n5hr 02min ago',
  '19.16 ',
  'N  ',
  '155.38 ',
  'W  ',
  '36',
  '',
  '2.6',
  ' ISLAND OF HAWAII, HAWAII',
  ''],
 ['2022-11-09   12:10:05.4\n5hr 03min ago',
  '44.05 ',
  'N  ',
  '13.31 ',
  'E  ',
  '26',
  '',
  '3.9',
  ' ADRIATIC SEA',
  ''],
 ['2022-11-09   12:02:56.2\n5hr 10min ago',
  '44.01 ',
  'N  ',
  '13.27 ',
  'E  ',
  '8',
  '',
  '3.1',
  ' ADRIATIC SEA',
  ''],
 ['2022-11-09   11:50:55.0\n5hr 22min ago',
  '8.40 ',
  'S  ',
  '119.82 ',
  'E  ',
  '142',
  '',
  '3.2',
  ' FLORES REGION, INDONESIA',
  ''],
 ['2022-11-09   11:46:06.2\n5hr 27min ago',
  '19.10 ',
  'N  ',
  '155.42 ',
  'W  ',
  '30',
  '',
  '2.0',
  ' ISLAND OF HAWAII, HAWAII',
  ''],
 ['2022-11-09   11:41:07.0\n5hr 32min ago',
  '2.98 ',
  'S  ',
  '140.05 ',
  'E  ',
  '16',
  '',
  '2.7',
  ' NEAR N COAST OF PAPUA, INDONESIA',
  ''],
 ['2022-11-09   11:10:29.0\n6hr 02min ago',
  '11.50 ',
  'N  ',
  '87.50 ',
  'W  ',
  '78',
  '',
  '2.7',
  ' NEAR COAST OF NICARAGUA',
  ''],
 ['2022-11-09   11:09:26.0\n6hr 03min ago',
  '18.21 ',
  'N  ',
  '103.59 ',
  'W  ',
  '5',
  '',
  '4.1',
  ' OFFSHORE MICHOACAN, MEXICO',
  ''],
 ['2022-11-09   11:08:33.7\n6hr 04min ago',
  '39.89 ',
  'N  ',
  '15.74 ',
  'E  ',
  '16',
  '',
  '2.6',
  ' SOUTHERN ITALY',
  ''],
 ['2022-11-09   11:03:23.9\n6hr 09min ago',
  '43.91 ',
  'N  ',
  '13.34 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  ''],
 ['2022-11-09   11:01:42.9\n6hr 11min ago',
  '43.90 ',
  'N  ',
  '13.24 ',
  'E  ',
  '10',
  '',
  '2.2',
  ' CENTRAL ITALY',
  '']]

In [210]:
cabeceras=driver.find_element(By.XPATH, '//*[@id="haut_tableau"]')

cabeceras=[c.text for c in cabeceras.find_elements(By.CLASS_NAME, 'th2')]


cabeceras

['Citizen\nResponse',
 'Date & Time\nUTC',
 'Latitude\ndegrees',
 'Longitude\ndegrees',
 'Depth\nkm',
 'Mag\n[+]',
 'Region name\n[+]',
 '']

In [214]:
cabeceras.pop(0)

'Citizen\nResponse'

In [216]:
cabeceras.pop(6)

''

In [217]:
cabeceras

['Date & Time\nUTC',
 'Latitude\ndegrees',
 'Longitude\ndegrees',
 'Depth\nkm',
 'Mag\n[+]',
 'Region name\n[+]']

In [213]:
df=pd.DataFrame(data, columns=cabeceras)

df.head()

ValueError: 8 columns passed, passed data had 13 columns

#### Count number of tweets by a given Twitter account.

You will need to include a ***try/except block*** for account names not found. 
<br>***Hint:*** the program should count the number of tweets for any provided account

In [182]:
# This is the url you will scrape in this exercise 
# You will need to add the account credentials to this url
url = 'https://twitter.com/carlosalcaraz'

In [183]:
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [196]:
tweets=driver.find_element(By.XPATH, '//*[@id="react-root"]/div/div/div[2]/main/div/div/div/div/div/div[1]/div[1]/div/div/div/div/div/div[2]/div/div')
tweets.text

'590 Tweets'

In [197]:
driver.quit()

#### Number of followers of a given twitter account

You will need to include a ***try/except block*** in case account/s name not found. 
<br>***Hint:*** the program should count the followers for any provided account

In [198]:
# This is the url you will scrape in this exercise 
# You will need to add the account credentials to this url
url = 'https://twitter.com/carlosalcaraz'

In [199]:
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [200]:
followers=driver.find_element(By.XPATH, '//*[@id="react-root"]/div/div/div[2]/main/div/div/div/div/div/div[3]/div/div/div/div/div[5]/div[2]/a/span[1]/span')
followers.text

'446.3K'

In [201]:
driver.quit()

#### List all language names and number of related articles in the order they appear in wikipedia.org

In [142]:
# This is the url you will scrape in this exercise
url = 'https://www.wikipedia.org/'

In [143]:
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [148]:
idioma=driver.find_elements(By.TAG_NAME, 'strong')
idioma[1].text

'English'

In [153]:
idiomas=[e.text.strip() for e in idioma]
idiomas[1:11]

['English',
 '日本語',
 'Español',
 'Русский',
 'Français',
 'Deutsch',
 'Italiano',
 '中文',
 'Português',
 'العربية']

In [154]:
driver.quit()

#### A list with the different kind of datasets available in data.gov.uk

In [155]:
# This is the url you will scrape in this exercise
url = 'https://data.gov.uk/'

In [156]:
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [158]:
uk=driver.find_elements(By.TAG_NAME, 'h3')
uk[0].text

'Business and economy'

In [160]:
datasets=[e.text.strip() for e in uk]
datasets

['Business and economy',
 'Crime and justice',
 'Defence',
 'Education',
 'Environment',
 'Government',
 'Government spending',
 'Health',
 'Mapping',
 'Society',
 'Towns and cities',
 'Transport',
 'Digital service performance',
 'Government reference data']

In [161]:
driver.quit()

#### Top 10 languages by number of native speakers stored in a Pandas Dataframe

In [162]:
# This is the url you will scrape in this exercise
url = 'https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers'

In [163]:
driver = webdriver.Chrome(PATH,options = opciones)
driver.get(url)

In [187]:
tabla=driver.find_element(By.XPATH, '//*[@id="mw-content-text"]/div[1]/table[1]/tbody')

filas=tabla.find_elements(By.TAG_NAME, 'tr')


data=[]


for f in filas:
    
    elemen=f.find_elements(By.TAG_NAME, 'td')
    
    tmp=[]
    
    for e in elemen:
        
        tmp.append(e.text)
        
    data.append(tmp)

    
data

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="mw-content-text"]/div[1]/table[1]/tbody"}
  (Session info: chrome=107.0.5304.87)
Stacktrace:
0   chromedriver                        0x0000000104fbc2c8 chromedriver + 4752072
1   chromedriver                        0x0000000104f3c463 chromedriver + 4228195
2   chromedriver                        0x0000000104b9fb18 chromedriver + 441112
3   chromedriver                        0x0000000104bdce21 chromedriver + 691745
4   chromedriver                        0x0000000104bdd061 chromedriver + 692321
5   chromedriver                        0x0000000104c185e4 chromedriver + 935396
6   chromedriver                        0x0000000104bfdd2d chromedriver + 826669
7   chromedriver                        0x0000000104c16134 chromedriver + 926004
8   chromedriver                        0x0000000104bfdb33 chromedriver + 826163
9   chromedriver                        0x0000000104bce9fd chromedriver + 633341
10  chromedriver                        0x0000000104bd0051 chromedriver + 639057
11  chromedriver                        0x0000000104f8930e chromedriver + 4543246
12  chromedriver                        0x0000000104f8da88 chromedriver + 4561544
13  chromedriver                        0x0000000104f956df chromedriver + 4593375
14  chromedriver                        0x0000000104f8e8fa chromedriver + 4565242
15  chromedriver                        0x0000000104f642cf chromedriver + 4391631
16  chromedriver                        0x0000000104fad5b8 chromedriver + 4691384
17  chromedriver                        0x0000000104fad739 chromedriver + 4691769
18  chromedriver                        0x0000000104fc381e chromedriver + 4782110
19  libsystem_pthread.dylib             0x00007ff8070c94e1 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8070c4f6b thread_start + 15

In [173]:
cabeceras=driver.find_element(By.XPATH, '//*[@id="mw-content-text"]/div[1]/table[1]/thead')

cabeceras=[c.text for c in cabeceras.find_elements(By.TAG_NAME, 'th')]

driver.quit()

cabeceras

['Language', 'Native speakers\n(millions)', 'Language family', 'Branch']

In [178]:
df=pd.DataFrame(data, columns=cabeceras)

df.head()

,Language,Native speakers\n(millions),Language family,Branch
0,"Mandarin Chinese\n(incl. Standard Chinese, but...",920,Sino-Tibetan,Sinitic
1,Spanish,475,Indo-European,Romance
2,English,373,Indo-European,Germanic
3,Hindi\n(excl. Urdu),344,Indo-European,Indo-Aryan
4,Bengali,234,Indo-European,Indo-Aryan

In [175]:
df.drop(['Language family', 'Branch'], axis = 'columns', inplace=True)

In [177]:
df.head()

,Language,Native speakers\n(millions)
0,"Mandarin Chinese\n(incl. Standard Chinese, but...",920
1,Spanish,475
2,English,373
3,Hindi\n(excl. Urdu),344
4,Bengali,234

In [181]:
driver.quit()

### BONUS QUESTIONS

#### Scrape a certain number of tweets of a given Twitter account.

In [ ]:
# This is the url you will scrape in this exercise 
# You will need to add the account credentials to this url
url = 'https://twitter.com/'

In [ ]:
# your code

#### IMDB's Top 250 data (movie name, Initial release, director name and stars) as a pandas dataframe

In [ ]:
# This is the url you will scrape in this exercise 
url = 'https://www.imdb.com/chart/top'

In [ ]:
# your code

#### Movie name, year and a brief summary of the top 10 random movies (IMDB) as a pandas dataframe.

In [ ]:
#This is the url you will scrape in this exercise
url = 'http://www.imdb.com/chart/top'

In [ ]:
#your code

#### Find the live weather report (temperature, wind speed, description and weather) of a given city.

In [ ]:
#https://openweathermap.org/current
city = city=input('Enter the city:')
url = 'http://api.openweathermap.org/data/2.5/weather?'+'q='+city+'&APPID=b35975e18dc93725acb092f7272cc6b8&units=metric'

In [ ]:
# your code

#### Book name,price and stock availability as a pandas dataframe.

In [ ]:
# This is the url you will scrape in this exercise. 
# It is a fictional bookstore created to be scraped. 
url = 'http://books.toscrape.com/'

In [ ]:
#your code